whitehand/cart/urls.py
from django.urls import re_path
from . import views


urlpatterns = [
    re_path(r'^$', views.cart_detail, name='cart_detail'),
    re_path(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    re_path(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

whitehand/orders/urls.py
from django.urls import re_path

from orders.views import order_create

urlpatterns = [
    re_path(r'^create/$', order_create, name='order_create'),
]

whitehand/whitehand/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as userviews
from handmade.views import *
from users.views import Login, Logout,my_user_profile,admin_tovars,update_tovar


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',index,name='index'),
    path('tovars',tovari, name='tovari'),
    path('tov/<int:id>/',list_tovar,name ='list_tovar'),
    path('tovars/category<int:id>',prodct_cat,name='prodct_cat'),
    path('search/',search,name = 'search'),
    path ('feed/',feedback,name='feedback'),
    path ('contact/',kontakt ,name='kontaktte'),
path ('politicy/',politicy ,name='politicy'),
path ('abous/',abous ,name='abous'),
    path('cart/', include(('cart.urls','cart'), namespace='cart')),
    path('ord/', include(('orders.urls','order'), namespace='orders')),
    path('register/', userviews.register, name='register'),
    path('login', Login.as_view(), name='login'),
    path('logout', Logout.as_view(), name='logout'),
    path('accounts/profile/', my_user_profile, name='my_profile'),
    path('accounts/admin/tovars/', admin_tovars, name='admin_tov'),
    path('accounts/admin/tovars/<int:id>/', update_tovar, name='one_tovar_adm'),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

whitehand/cart/models.py
from django.db import models

# Create your models here.

whitehand/cart/forms.py
from django import forms

class CartAddProductForm(forms.Form):
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

whitehand/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from handmade.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')

def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    return render(request, 'cart/cart_info.html', {'cart': cart})

whitehand/templates/cart/cart_info.html
{% extends 'handmade/index.html' %}
{%block oznokom%}{%endblock%}
{%block main%}
    <p class="text-right">
        <a href="{% url "tovari" %}" class="button light">Продолжить покупки</a>
    </p>

<body>
<div id="w">
    <header id="title">
        <h1>Корзина</h1>
    </header>
    <div id="page">
        <table id="cart">
            <thead>
            <tr>
                <th class="second">Кол-во</th>
                <th class="third">Товар</th>
                <th class="fourth">Итог.Цена</th>
                <th class="fifth">&nbsp;</th>
            </tr>
            </thead>
            <tbody>
            <!-- shopping cart contents -->
            {% for item in cart %}
            {% with product=item.product %}
            <tr class="productitm">
                <!-- http://www.inkydeals.com/deal/ginormous-bundle/ -->
                <td>{{ item.quantity }}</td>
                <td>{{product.name}}</td>
                <td>{{ item.total_price }}Р</td>
                <td><a href="{% url "cart:cart_remove" product.id%}"><span class="remove"><img src="https://i.imgur.com/h1ldGRr.png" alt="X"></span></a></td>
            </tr>
{% endwith %}
        {% endfor %}
            <!-- subtotal -->
            <tr class="extracosts">
            </tr>
            <tr class="totalprice">
                <td class="light">Итого:</td>
                <td colspan="2">&nbsp;</td>
                <td colspan="2"><span class="thick">{{ cart.get_total_price }}Р</span></td>
            </tr>

            <!-- checkout btn -->
            <tr class="checkoutrow">
                <td colspan="5" class="checkout">
                    <a href="{%url 'orders:order_create'%}" <button id="submitbtn">Заказать</button></a>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
</div>
</body>
{%endblock%}

whitehand/templates/cart/order_create.html
{% extends 'handmade/index.html' %}
{%block oznokom%} {%endblock%}
{%block main%}
    <h1>Страница заказа</h1>
    <div class="order-info">
        <h3>Заказ</h3>
        <ul>
            {% for item in cart %}
                <li>
                    {{ item.quantity }}x {{ item.product.name }}
                    <span>${{ item.total_price }}</span>
                </li>
            {% endfor %}
        </ul>
        <p>Total: ${{ cart.get_total_price }}</p>
    </div>
    <form method="POST">
        {% csrf_token %}
        <label>Город</label>
    <input name="city" required>
        <label>Адрес</label>
    <input name="address" required>
        <label>Почтовый индекс</label>
    <input name="postal_code" required>
        <input type="submit" value="Заказать">
    </form>
    {%endblock%}