whitehand/cart/urls.py
from django.urls import re_path
from . import views


urlpatterns = [
    re_path(r'^$', views.cart_detail, name='cart_detail'),
    re_path(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    re_path(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

whitehand/whitehand/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as userviews
from handmade.views import *
from users.views import Login, Logout,my_user_profile,admin_tovars,update_tovar


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',index,name='index'),
    path('tovars',tovari, name='tovari'),
    path('tov/<int:id>/',list_tovar,name ='list_tovar'),
    path('tovars/category<int:id>',prodct_cat,name='prodct_cat'),
    path('search/',search,name = 'search'),
    path ('feed/',feedback,name='feedback'),
    path ('contact/',kontakt ,name='kontaktte'),
path ('politicy/',politicy ,name='politicy'),
path ('abous/',abous ,name='abous'),
    path('cart/', include(('cart.urls','cart'), namespace='cart')),
    path('ord/', include(('orders.urls','order'), namespace='orders')),
    path('register/', userviews.register, name='register'),
    path('login', Login.as_view(), name='login'),
    path('logout', Logout.as_view(), name='logout'),
    path('accounts/profile/', my_user_profile, name='my_profile'),
    path('accounts/admin/tovars/', admin_tovars, name='admin_tov'),
    path('accounts/admin/tovars/<int:id>/', update_tovar, name='one_tovar_adm'),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

whitehand/handmade/models.py
from django.db import models

class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Size (models.Model):
    heigh = models.IntegerField()
    width = models.IntegerField()

    def __str__(self):
        return f"id: {self.id}, Ширина: {self.width}, Высота: {self.heigh}"

class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    size = models.ForeignKey(Size, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to='product_images')
    manufacturer = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Review(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    rating = models.PositiveIntegerField()
    comment = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Review by {self.user.username} for {self.product.name}"


class Feedback(models.Model):
    name=models.CharField(max_length=100, verbose_name='Имя')
    masage=models.TextField(verbose_name='Сообщение')
    number=models.DecimalField(max_digits=12, decimal_places=0)

    def __str__(self):
        return self.name

whitehand/handmade/forms.py
from .models import *
from django import forms


class Feedb(forms.ModelForm):
    class Meta:
        model = Feedback
        fields = ['name', 'masage', 'number']

class CategoryFilterForm(forms.Form):
    categories = forms.ModelMultipleChoiceField(
        queryset=Category.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        label="Категории"
    )

whitehand/handmade/views.py
from django.db.models import Q
from django.shortcuts import render

from handmade.models import *

from handmade.forms import Feedb,CategoryFilterForm

from cart.forms import CartAddProductForm


def index(request):
    categs = Category.objects.all()
    data={
        'categs':categs
    }
    return render(request,'handmade/index.html',data)

def tovari(request):
    producti = Product.objects.all()
    categs = Category.objects.all()
    form = CategoryFilterForm(request.GET or None)
    cart_product_form = CartAddProductForm()
    if form.is_valid():
        categories = form.cleaned_data['categories']
        producti = producti.filter(category__in=categories)

    data = {
        'producti':producti,
        'categs': categs,
        'form': form,
        'cart_product_form':cart_product_form
    }
    return render (request, 'handmade/main.html',data)

def list_tovar (request,id):
    categs = Category.objects.all()
    product = Product.objects.get(id = id)
    manufacturer = Product.objects.all()
    data = {
        'categs': categs,
        'product':product,
        'manufacturer':manufacturer
    }
    return render (request, 'handmade/list.html',data)

def prodct_cat(request,id):
    categs = Category.objects.all()
    producti = Product.objects.filter(category__id = id)
    data = {
        'producti':producti,
        'categs': categs,
    }
    return render(request, 'handmade/main.html', data)


def search(request):
    query = request.GET.get('query', None)
    if query == '':
        query = 'none'
    query = request.GET.get('q')
    product = Product.objects.filter(
        Q(name__icontains=query)
    ).all()
    data={
        'product': product,
        'query':query
    }
    return render(request,'handmade/main.html',data)

def feedback(request):
    if request.method == 'POST':
        fedd = Feedb(request.POST)
        if fedd.is_valid():
            fedd.save()
    else:
        fedd = Feedb()

    data={
        'fedd':fedd
    }
    return render(request, 'handmade/index.html',data)


def abous(request):
    categs = Category.objects.all()
    data = {
        'categs': categs
    }
    return render(request, 'handmade/onas.html',data)

def politicy(request):
    categs = Category.objects.all()
    data = {
        'categs': categs
    }
    return render(request, 'handmade/politic.html',data)

def kontakt(request):
    categs = Category.objects.all()
    data = {
        'categs': categs
    }
    return render(request, 'handmade/kontakt.html',data)

whitehand/templates/handmade/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Главная</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href=" https://use.fontawesome.com/releases/v6.4.4/css/all.css">
</head>
<body>
{%block header%}
    <div class="main">
        <header>
          <div id="burger-menu">
            <span></span>
          </div>
          <div id="menu">
              <ul>
                <li><a href="{%url 'index' %}">Главная</a></li>
                <li><a href="{%url 'tovari' %}">Товары</a></li>
                <li><a href="{%url 'kontaktte' %}">Контакты</a></li>
                <li><a href="#">О нас</a></li>
                                    <li><a href="{%url 'cart:cart_detail'%}">Корзина</a></li>
                {% if user.is_authenticated %}
                  <li><a href="{%url 'my_profile' %}">Профиль</a></li>
                {% else %}
                  <li><a href="{%url 'register' %}">Регистрация</a></li>
                {% endif %}
              </ul>
          </div>
            <div class="logo">
                <img src='{% static "img/logo.png" %}' alt="">
            </div>
            <div class="menu">
              <ul>
                  <li><a href="{%url 'index' %}">Главная</a></li>
                  <div class="dropdown">
                      <button class="dropbtn"><li><a href="{%url 'tovari' %}">Товары</a></li> </button>
                      <div class="dropdown-content">
                          {%for i in categs%}
                        <a href="{%url 'prodct_cat' i.id%}">{{i}}</a>
                          {% endfor %}
                      </div>
                    </div>
                  <li><a href="{%url 'kontaktte' %}">Контакты</a></li>
                  <li><a href="{%url 'abous'%}">О нас</a></li>
              </ul>
          </div>
            <div class="link">
                <a class="link_korzina" href="{%url 'cart:cart_detail'%}"><img src='{% static "img/korzina.png" %}' alt=""></a>
                {% if user.is_authenticated %}
                 <a class="link_user" href="{%url 'my_profile' %}"><img  src='{% static "img/user.png" %}' alt=""></a>
                {% else %}
                 <a class="link_user" href="{%url 'register' %}"><img  src='{% static "img/user.png" %}' alt=""></a>
                {% endif %}
            </div>
            <div class="search-box">
                <form action="{%url 'search'%}" method="get">
              <button class="btn-search"><i class="fas fa-search"></i><img src='{% static "img/lupa.png" %}' alt=""></button>
              <input name="q" type="text" class="input-search" placeholder="Поиск">
                    </form>
            </div>
        </header>
        {% endblock %}
        {%block oznokom%}
        <div class="oznokom">
            <img src="{% static 'img/people.png' %}" alt="">
            <div class="oznokom-butt">
            <h1>В нᴀɯᴇ ʙᴩᴇʍя, ᴋоᴦдᴀ ᴛᴇхноᴧоᴦии ᴄᴛᴩᴇʍиᴛᴇᴧьно ᴩᴀзʙиʙᴀюᴛᴄя и ᴀʙᴛоʍᴀᴛизᴀция зᴀниʍᴀᴇᴛ ʙᴄё боᴧьɯᴇ ᴨᴩоᴄᴛᴩᴀнᴄᴛʙᴀ, ᴩучныᴇ ᴩᴀбоᴛы нᴇ уᴛᴩᴀчиʙᴀюᴛ ᴄʙоᴇй ᴀᴋᴛуᴀᴧьноᴄᴛи. нᴀобоᴩоᴛ, они ᴄᴛᴀноʙяᴛᴄя ʙᴄё боᴧᴇᴇ ᴨоᴨуᴧяᴩныʍи. ᴩучныᴇ ᴩᴀбоᴛы – ϶ᴛо нᴇ ᴛоᴧьᴋо ᴄᴨоᴄоб ᴄоздᴀния униᴋᴀᴧьных и ᴋᴀчᴇᴄᴛʙᴇнных издᴇᴧий,
                но и ʙозʍожноᴄᴛь ʙыᴩᴀзиᴛь ᴄʙою индиʙидуᴀᴧьноᴄᴛь и ᴛʙоᴩчᴇᴄᴋий ᴨоᴛᴇнциᴀᴧ.</h1>
                <a href="{%url 'tovari' %}">Посмотреть изделия</a>
            </div>
        </div>
    </div>
{%endblock%}
{% block main %}
    <div class="slider">
      <div class="flexslider">
        <ul class="slides">
          <li>
            <img src='{% static "img/slider1.png" %}' />
          </li>
          <li>
            <img src='{% static "img/slider2.png" %}' />
          </li>
          <li>
            <img src='{% static "img/slider3.png" %}' />
          </li>
          <li>
            <img src='{% static "img/slider4.png"%}' />
          </li>
        </ul>
      </div>
    </div>
          <div class="inform">
              <div class="block">
                <img src="{% static 'img/box.png' %}" alt="Open box">
                    <p>Достоверная информация от наших продавцов</p>
              </div>
              <div class="block1">
                <img src="{% static 'img/peoples.png' %}" alt="99% Service">
                  <p>99,9% наших посетителей довольны сервисом </p>
              </div>
              <div class="block2">
                <img src="{% static 'img/galka.png'%}" alt="Garant quality">
                <p>Гарантия качества</p>
              </div>
        </div>
        {% endblock %}

        {%block footer%}
        <footer class="footer">
          <div class="container">
            <div class="row">
              <div class="footer-col">
                <h4>Компания</h4>
                <ul>
                  <li><a href="{%url 'abous'%}">О нас</a></li>
                  <li><a href="#">Наши услуги</a></li>
                  <li><a href="{%url 'politicy'%}">Политика конфиденциальности</a></li>
                </ul>
              </div>
              <div class="footer-col">
                <h4>Помощь</h4>
                <ul>
                  <li><a class="open_modal" href="#">Обратная связь</a></li>
                  <li><a href="#">Доставка</a></li>
                </ul>
              </div>
              <div class="footer-col">
                <h4>Магазин</h4>
                <ul>
                  <li><a href="{%url 'tovari'%}">Посмотреть</a></li>
                </ul>
              </div>
              <div class="footer-col">
                <h4>Сообщества</h4>
                <div class="social-links">
                  <a href="https://t.me/"><i class="fab fa-facebook-f"><svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-telegram" viewBox="0 0 16 16">
                    <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM8.287 5.906c-.778.324-2.334.994-4.666 2.01-.378.15-.577.298-.595.442-.03.243.275.339.69.47l.175.055c.408.133.958.288 1.243.294.26.006.549-.1.868-.32 2.179-1.471 3.304-2.214 3.374-2.23.05-.012.12-.026.166.016.047.041.042.12.037.141-.03.129-1.227 1.241-1.846 1.817-.193.18-.33.307-.358.336a8.154 8.154 0 0 1-.188.186c-.38.366-.664.64.015 1.088.327.216.589.393.85.571.284.194.568.387.936.629.093.06.183.125.27.187.331.236.63.448.997.414.214-.02.435-.22.547-.82.265-1.417.786-4.486.906-5.751a1.426 1.426 0 0 0-.013-.315.337.337 0 0 0-.114-.217.526.526 0 0 0-.31-.093c-.3.005-.763.166-2.984 1.09z"/>
                  </svg></i></a>
                  <a href="https://vk.com/"><i class="fab fa-twitter"><svg xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="40" height="40" viewBox="0 0 50 50"
                    style="fill:#FFFFFF;">
                        <path d="M25,2C12.318,2,2,12.318,2,25s10.318,23,23,23c12.683,0,23-10.318,23-23S37.683,2,25,2z M34.973,29.535 c2.237,1.986,2.702,2.695,2.778,2.816C38.678,33.821,36.723,34,36.723,34h-4.12c0,0-1.003,0.011-1.86-0.557 c-1.397-0.915-2.86-2.689-3.888-2.381C25.992,31.32,26,32.486,26,33.483C26,33.84,25.693,34,25,34s-0.981,0-1.288,0 c-2.257,0-4.706-0.76-7.149-3.313c-3.456-3.609-6.487-10.879-6.487-10.879s-0.179-0.366,0.016-0.589 c0.221-0.25,0.822-0.218,0.822-0.218L14.909,19c0,0,0.376,0.071,0.646,0.261c0.223,0.156,0.347,0.454,0.347,0.454 s0.671,2.216,1.526,3.629c1.67,2.758,2.447,2.828,3.014,2.531C21.27,25.445,21,22.513,21,22.513s0.037-1.259-0.395-1.82 c-0.333-0.434-0.97-0.665-1.248-0.701c-0.225-0.029,0.151-0.423,0.63-0.648C20.627,19.059,21.498,18.986,23,19 c1.169,0.011,1.506,0.081,1.962,0.186C26.341,19.504,26,20.343,26,23.289c0,0.944-0.13,2.271,0.582,2.711 c0.307,0.19,1.359,0.422,3.231-2.618c0.889-1.442,1.596-3.834,1.596-3.834s0.146-0.263,0.373-0.393 c0.232-0.133,0.225-0.13,0.543-0.13S35.832,19,36.532,19c0.699,0,1.355-0.008,1.468,0.402c0.162,0.589-0.516,2.607-2.234,4.797 C32.943,27.793,32.63,27.457,34.973,29.535z"></path>
                    </svg></i></a>
                  <a href="https://www.whatsapp.com/"><i class="fab fa-instagram"><svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-whatsapp" viewBox="0 0 16 16">
                    <path d="M13.601 2.326A7.854 7.854 0 0 0 7.994 0C3.627 0 .068 3.558.064 7.926c0 1.399.366 2.76 1.057 3.965L0 16l4.204-1.102a7.933 7.933 0 0 0 3.79.965h.004c4.368 0 7.926-3.558 7.93-7.93A7.898 7.898 0 0 0 13.6 2.326zM7.994 14.521a6.573 6.573 0 0 1-3.356-.92l-.24-.144-2.494.654.666-2.433-.156-.251a6.56 6.56 0 0 1-1.007-3.505c0-3.626 2.957-6.584 6.591-6.584a6.56 6.56 0 0 1 4.66 1.931 6.557 6.557 0 0 1 1.928 4.66c-.004 3.639-2.961 6.592-6.592 6.592zm3.615-4.934c-.197-.099-1.17-.578-1.353-.646-.182-.065-.315-.099-.445.099-.133.197-.513.646-.627.775-.114.133-.232.148-.43.05-.197-.1-.836-.308-1.592-.985-.59-.525-.985-1.175-1.103-1.372-.114-.198-.011-.304.088-.403.087-.088.197-.232.296-.346.1-.114.133-.198.198-.33.065-.134.034-.248-.015-.347-.05-.099-.445-1.076-.612-1.47-.16-.389-.323-.335-.445-.34-.114-.007-.247-.007-.38-.007a.729.729 0 0 0-.529.247c-.182.198-.691.677-.691 1.654 0 .977.71 1.916.81 2.049.098.133 1.394 2.132 3.383 2.992.47.205.84.326 1.129.418.475.152.904.129 1.246.08.38-.058 1.171-.48 1.338-.943.164-.464.164-.86.114-.943-.049-.084-.182-.133-.38-.232z"/>
                  </svg></i></a>
                </div>
              </div>
            </div>
          </div>
       </footer>
    </div>

    <form class="obratnuj-zvonok" action="{% url 'feedback' %}" method='post'>
{% csrf_token %}
        <div class="blockformodal">
      <div class="form-zvonok">
        <p class="close_modal">X</p>
        <div>
          <label>Имя <span>*</span></label>
          <input type='text' name='name' required></div>
        <div>
          <label>Номер телефона (с кодом) <span>*</span></label>
          <input type='text' name='number' required></div>
        <div>
          <label>Сообщение</label>
          <input type='text' name='masage'>
        </div>
        <input class="bot-send-mail" type='submit' value='Послать заявку'>
      </div>
        </div>
      </form>
</body>
<link rel="stylesheet" href={% static 'css/flexslider.css' %} type="text/css" media="screen" />
 <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script defer src={% static 'js/jquery.flexslider-min.js' %}></script>
  <script src={% static 'js/main.js' %}></script>
</html>
{% endblock %}

whitehand/templates/handmade/kontakt.html
{% extends 'handmade/index.html' %}
{%block oznokom%} {%endblock%}
{%block main%}

    <content>
        <div class="content">
            <div class="maps">  
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d4612.442243398847!2d46.39151757170924!3d55.51224192694809!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x415b20ea60ab9805%3A0x58443b41226f8019!2z0KjRg9C80LXRgNC70LjQvdGB0LrQuNC5INCf0L7Qu9C40YLQtdGF0L3QuNGH0LXRgdC60LjQuSDQotC10YXQvdC40LrRg9C8!5e1!3m2!1sru!2sru!4v1683212621706!5m2!1sru!2sru" width="700" height="600" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>

                 <p>Адрес
                       ул. Некрасова, 62</p>
                    <p> Контакты
                        +7 (83536) 2-14-21</p>
                    <p> Время работы
                        Открыто до 16:30</p>
            </div>
        </div>
    </content>
 {%endblock%}

whitehand/templates/handmade/list.html
{% extends 'handmade/index.html' %}
{% load static %}
{%block oznokom%} {%endblock%}
{%block main%}

    <div class="card">
      <div class="card__title">
        <div class="icon">
          <a href="{%url 'tovari' %}"><i class="fa fa-arrow-left"></i></a>
        </div>
        <h3>New products</h3>
      </div>
      <div class="card__body">
        <div class="half">
          <div class="featured_text">
            <h2>Производитель:{{product.manufacturer}}</h2>
            <p class="sub">Название:{{product.name}}</p>
            <p class="price">{{product.price}}P</p>
          </div>
          <div class="image">
            <img src="{{product.image.url}}" alt="">
          </div>
        </div>
        <div class="half">
          <div class="description">
            <h2>{{product.description}}</h2>
          </div>
<!--        <span class="stock"><i class="fa fa-pen"></i> In stock</span>-->
<!--          <div class="reviews">-->
<!--            <ul class="stars">-->
<!--              <li><i class="fa fa-star"></i></li>-->
<!--              <li><i class="fa fa-star"></i></li>-->
<!--              <li><i class="fa fa-star"></i></li>-->
<!--              <li><i class="fa fa-star"></i></li>-->
<!--              <li><i class="fa fa-star-o"></i></li>-->
<!--            </ul>-->
<!--            <span>(64 reviews)</span>-->
          </div>
        </div>
      </div>
      <div class="card__footer">
        <div class="recommend">
        </div>
        <div class="action">
        </div>
      </div>
    </div>
 {%endblock%}

whitehand/templates/handmade/main.html
{% extends 'handmade/index.html' %}
{%block oznokom%} {%endblock%}
{%block main%}

            <div class="centr">
                <div class="blockk">
                <form method="GET" class="form_filter">
              {{ form.as_p }}
              <button type="submit">Применить фильтр</button>
            </form>
                    {%if query%}
                     {%for i in product%}
                    <div class="wrapper">
                        <a href="{%url 'list_tovar' i.id%}"><div class="container">

                          <div class="top"><img src="{{i.image.url}}" alt=""> </div>
                          <div class="bottom">
                            <div class="left">
                              <div class="details">
                                <h2>{{i.name}}</h2>
                                <p>{{i.price}} р</p>
                              </div>
                              <div class="buy"><i class="material-icons"><svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" fill="currentColor" class="bi bi-cart-check" viewBox="0 0 16 16">
                                <path d="M11.354 6.354a.5.5 0 0 0-.708-.708L8 8.293 6.854 7.146a.5.5 0 1 0-.708.708l1.5 1.5a.5.5 0 0 0 .708 0l3-3z"/>
                                <path d="M.5 1a.5.5 0 0 0 0 1h1.11l.401 1.607 1.498 7.985A.5.5 0 0 0 4 12h1a2 2 0 1 0 0 4 2 2 0 0 0 0-4h7a2 2 0 1 0 0 4 2 2 0 0 0 0-4h1a.5.5 0 0 0 .491-.408l1.5-8A.5.5 0 0 0 14.5 3H2.89l-.405-1.621A.5.5 0 0 0 2 1H.5zm3.915 10L3.102 4h10.796l-1.313 7h-8.17zM6 14a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm7 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0z"/>
                              </svg></i></div>
                            </div>
                            <div class="right">
                              <div class="done"><i class="material-icons">done</i></div>
                              <div class="details">
                                <h1>Chair</h1>
                                <p>Added to your cart</p>
                              </div>
                              <div class="remove"><i class="material-icons">clear</i></div>
                            </div>
                          </div>
                        </div>
                        <div class="inside">
                          <div class="icon"><i class="material-icons"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-info-circle" viewBox="0 0 16 16">
                            <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                            <path d="m8.93 6.588-2.29.287-.082.38.45.083c.294.07.352.176.288.469l-.738 3.468c-.194.897.105 1.319.808 1.319.545 0 1.178-.252 1.465-.598l.088-.416c-.2.176-.492.246-.686.246-.275 0-.375-.193-.304-.533L8.93 6.588zM9 4.5a1 1 0 1 1-2 0 1 1 0 0 1 2 0z"/>
                          </svg></i></div>
                          <div class="contents">
                            <table>
                              <tr>
                                <th>Ширина: {{i.size.width}}</th>
                                <th>Высота: {{i.size.heigh}}</th>
                              </tr>
                            </table>
                          </div>
                        </div>
                      </div>
                    </a>
                        {% endfor %}

                    {%endif%}
                        {%for i in producti%}
                    <div class="wrapper">
                        <a href="{%url 'list_tovar' i.id%}"><div class="container">

                          <div class="top"><img src="{{i.image.url}}" alt=""> </div>
                          <div class="bottom">
                            <div class="left">
                              <div class="details">
                                <h2>{{i.name}}</h2>
                                <p>{{i.price}} р</p>
                              </div>
                              <div class="buy">
                                  <form action="{% url "cart:cart_add" i.id %}" method="post">
    {{ cart_product_form }}
    {% csrf_token %}
    <input type="submit" value="В корзину">
</form><i class="material-icons"><svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" fill="currentColor" class="bi bi-cart-check" viewBox="0 0 16 16">
                                <path d="M11.354 6.354a.5.5 0 0 0-.708-.708L8 8.293 6.854 7.146a.5.5 0 1 0-.708.708l1.5 1.5a.5.5 0 0 0 .708 0l3-3z"/>
                                <path d="M.5 1a.5.5 0 0 0 0 1h1.11l.401 1.607 1.498 7.985A.5.5 0 0 0 4 12h1a2 2 0 1 0 0 4 2 2 0 0 0 0-4h7a2 2 0 1 0 0 4 2 2 0 0 0 0-4h1a.5.5 0 0 0 .491-.408l1.5-8A.5.5 0 0 0 14.5 3H2.89l-.405-1.621A.5.5 0 0 0 2 1H.5zm3.915 10L3.102 4h10.796l-1.313 7h-8.17zM6 14a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm7 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0z"/>
                              </svg></i></div>
                            </div>
                            <div class="right">
                              <div class="done"><i class="material-icons">done</i></div>
                              <div class="details">
                                <h1>Chair</h1>
                                <p>Added to your cart</p>
                              </div>
                              <div class="remove"><i class="material-icons">clear</i></div>
                            </div>
                          </div>
                        </div>
                        <div class="inside">
                          <div class="icon"><i class="material-icons"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-info-circle" viewBox="0 0 16 16">
                            <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                            <path d="m8.93 6.588-2.29.287-.082.38.45.083c.294.07.352.176.288.469l-.738 3.468c-.194.897.105 1.319.808 1.319.545 0 1.178-.252 1.465-.598l.088-.416c-.2.176-.492.246-.686.246-.275 0-.375-.193-.304-.533L8.93 6.588zM9 4.5a1 1 0 1 1-2 0 1 1 0 0 1 2 0z"/>
                          </svg></i></div>
                          <div class="contents">
                            <table>
                              <tr>
                                <th>Ширина: {{i.size.width}}</th>
                                <th>Высота: {{i.size.heigh}}</th>
                              </tr>
                            </table>
                          </div>
                        </div>
                      </div>
                    </a>
                        {% endfor %}

             </div>
        </div>
 {%endblock%}