whitehand/cart/urls.py
from django.urls import re_path
from . import views


urlpatterns = [
    re_path(r'^$', views.cart_detail, name='cart_detail'),
    re_path(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    re_path(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

whitehand/whitehand/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as userviews
from handmade.views import *
from users.views import Login, Logout,my_user_profile,admin_tovars,update_tovar


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',index,name='index'),
    path('tovars',tovari, name='tovari'),
    path('tov/<int:id>/',list_tovar,name ='list_tovar'),
    path('tovars/category<int:id>',prodct_cat,name='prodct_cat'),
    path('search/',search,name = 'search'),
    path ('feed/',feedback,name='feedback'),
    path ('contact/',kontakt ,name='kontaktte'),
path ('politicy/',politicy ,name='politicy'),
path ('abous/',abous ,name='abous'),
    path('cart/', include(('cart.urls','cart'), namespace='cart')),
    path('ord/', include(('orders.urls','order'), namespace='orders')),
    path('register/', userviews.register, name='register'),
    path('login', Login.as_view(), name='login'),
    path('logout', Logout.as_view(), name='logout'),
    path('accounts/profile/', my_user_profile, name='my_profile'),
    path('accounts/admin/tovars/', admin_tovars, name='admin_tov'),
    path('accounts/admin/tovars/<int:id>/', update_tovar, name='one_tovar_adm'),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

whitehand/users/models.py
from django.db import models

# Create your models here.

whitehand/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

from handmade.models import Product,Size


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class ProductUpdateForm(forms.ModelForm):
    name = forms.CharField(max_length=100, required=False)
    description = forms.CharField(widget=forms.Textarea, required=False)
    price = forms.DecimalField(max_digits=10, decimal_places=2, required=False)
    manufacturer = forms.CharField(max_length=100, required=False)

    class Meta:
        model = Product
        fields = ['name','manufacturer','price','description']

whitehand/users/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.views import LogoutView, LoginView

from .forms import UserRegisterForm, ProductUpdateForm
from django.shortcuts import render, redirect
from django.contrib import messages

from handmade.models import Product,Category,Size


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Создан аккаунт {username}!')
            return redirect('Login')
    else:
        form = UserRegisterForm()
    return render(request, 'users/register.html', {'form': form})

class Logout(LogoutView):
    form_class = AuthenticationForm
    template_name = 'users/login.html'

class Login(LoginView):
    form_class = AuthenticationForm
    template_name = 'users/login.html'

@login_required
def my_user_profile(request):
    return render(request, 'users/profile.html')

@login_required
def admin_tovars(request):
    if request.user.is_superuser:
        producti = Product.objects.all()
        data={
            'producti':producti
        }
    return render(request,'users/uprav_tovars.html',data)

@login_required
def update_tovar(request,id):
    if request.user.is_superuser:
        product = Product.objects.get(id=id)
        if request.method == 'POST':
            form = ProductUpdateForm(request.POST, instance=product)
            if form.is_valid():
                form.save()
                return redirect(admin_tovars)
        else:
            categs = Category.objects.all()
            product = Product.objects.get(id=id)
            form = ProductUpdateForm(instance=product)
            manufacturer = Size.objects.all()
            data={
                'categs': categs,
                'product': product,
                'manufacturer': manufacturer,
                'form':form
            }
            return render(request,'users/update_tovar.html',data)

whitehand/users/templates/users/login.html
{% extends 'handmade/index.html' %}
{% load crispy_forms_tags %}
{% load static %}
{%block oznokom%} {%endblock%}
{%block main%}
<div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <label for="username">Имя пользователя:</label>
        <input type="text" id="username" name="username" required>

        <label for="password">Пароль:</label>
        <input type="password" id="password" name="password" required>

                <button class="btn btn-outline-info" type="submit">Вход</button>
        </form>

    </div>
{%endblock%}

whitehand/users/templates/users/profile.html
{% extends 'handmade/index.html' %}
{%block oznokom%} {%endblock%}
{% load static %}
{%block main%}

<div class="wrapper1">
    <div class="profile">
        <div class="overlay">
            <div class="about d-flex flex-column">
                <h4>{{request.user.username}}</h4>
                <span>{{ request.user.email }}</span>
            </div>
            <ul class="social-icons">
<form class="exituser" method="POST" action="{%url "logout"%}">{% csrf_token %}
              <button> <li><img src="{% static 'img/door.png' %}" alt=""></li></button>
</form>
                {% if request.user.is_superuser %}
                <li><a href="{%url 'admin_tov'%}"><img src="{% static 'img/man.png' %}" alt=""></a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>

{%endblock%}

whitehand/users/templates/users/register.html
{% extends 'handmade/index.html' %}
{% load crispy_forms_tags %}
{% load static %}
{%block oznokom%} {%endblock%}
{%block main%}
<div class="content-section">
        <form method="POST" >
            {% csrf_token %}

            <label for="username">Имя пользователя:</label>
        <input type="text" id="username" name="username" required>

        <label for="email">E-mail:</label>
        <input type="email" id="email" name="email" required>

        <label for="password1">Пароль:</label>
        <input type="password" id="password1" name="password1" required>
            <label for="password2">Повторите пароль:</label>
        <input type="password" id="password2" name="password2" required>
                <button class="btn btn-outline-info" type="submit">Регистрация</button>
        </form>
            <p class="textmyreg">Чтобы войти нажмите <a href="{%url 'login'%}">Вход</a></p>
    </div>
{%endblock%}

whitehand/users/templates/users/update_tovar.html
{% extends 'handmade/index.html' %}
{% load static %}
{%block oznokom%} {%endblock%}
{%block main%}

    <div class="card">
      <div class="card__title">
        <div class="icon">
          <a href="{%url 'tovari' %}"><i class="fa fa-arrow-left"></i></a>
        </div>
        <h3>New products</h3>
      </div>
      <div class="card__body">
        <div class="half">
          <div class="featured_text">
            <h2>Производитель:{{product.manufacturer}}</h2>
            <p class="sub">Название:{{product.name}}</p>
            <p class="price">{{product.price}}P</p>
          </div>
          <div class="image">
            <img src="{{product.image.url}}" alt="">
          </div>
        </div>
        <div class="half">
          <div class="description">
            <h2>{{product.description}}</h2>
          </div>
          </div>
        </div>
      </div>
      <div class="card__footer">
        <div class="recommend">
        </div>
        <div class="action">
        </div>
      </div>
    </div>
<div class="admin_upr_prod">
  <form method="POST">
    {% csrf_token %}
    <div>
    <label for="id_name">Name:</label>
<input type="text" name="name" value="{{product.name}}" maxlength="100" id="id_name">
</div>
    <div>
    <label for="id_manufacturer">Manufacturer:</label>
<input type="text" name="manufacturer" value="{{product.manufacturer}}" maxlength="100" id="id_manufacturer">
</div>
    <div>
    <label for="id_price">Price:</label>
<input type="number" name="price" value="{{product.price}}"  step="0.01" id="id_price">
</div>
    <div>
    <label for="id_description">Description:</label>
<textarea name="description" cols="30" rows="5" id="id_description">{{product.description}}</textarea>
</div>
    <div>
</div>

  <input type="submit" value="Изменить">
    </form>
  </div>
 {%endblock%}

whitehand/users/templates/users/uprav_tovars.html
{% extends 'handmade/index.html' %}
{%block oznokom%} {%endblock%}
{%block main%}

{%for i in product%}
                    <div class="wrapper">
                        <a href="{%url 'list_tovar' i.id%}"><div class="container">

                          <div class="top"><img src="{{i.image.url}}" alt=""> </div>
                          <div class="bottom">
                            <div class="left">
                              <div class="details">
                                <h2>{{i.name}}</h2>
                                <p>{{i.price}} р</p>
                              </div>
                              <div class="buy"><i class="material-icons"><svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" fill="currentColor" class="bi bi-cart-check" viewBox="0 0 16 16">
                                <path d="M11.354 6.354a.5.5 0 0 0-.708-.708L8 8.293 6.854 7.146a.5.5 0 1 0-.708.708l1.5 1.5a.5.5 0 0 0 .708 0l3-3z"/>
                                <path d="M.5 1a.5.5 0 0 0 0 1h1.11l.401 1.607 1.498 7.985A.5.5 0 0 0 4 12h1a2 2 0 1 0 0 4 2 2 0 0 0 0-4h7a2 2 0 1 0 0 4 2 2 0 0 0 0-4h1a.5.5 0 0 0 .491-.408l1.5-8A.5.5 0 0 0 14.5 3H2.89l-.405-1.621A.5.5 0 0 0 2 1H.5zm3.915 10L3.102 4h10.796l-1.313 7h-8.17zM6 14a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm7 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0z"/>
                              </svg></i></div>
                            </div>
                            <div class="right">
                              <div class="done"><i class="material-icons">done</i></div>
                              <div class="details">
                                <h1>Chair</h1>
                                <p>Added to your cart</p>
                              </div>
                              <div class="remove"><i class="material-icons">clear</i></div>
                            </div>
                          </div>
                        </div>
                        <div class="inside">
                          <div class="icon"><i class="material-icons"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-info-circle" viewBox="0 0 16 16">
                            <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                            <path d="m8.93 6.588-2.29.287-.082.38.45.083c.294.07.352.176.288.469l-.738 3.468c-.194.897.105 1.319.808 1.319.545 0 1.178-.252 1.465-.598l.088-.416c-.2.176-.492.246-.686.246-.275 0-.375-.193-.304-.533L8.93 6.588zM9 4.5a1 1 0 1 1-2 0 1 1 0 0 1 2 0z"/>
                          </svg></i></div>
                          <div class="contents">
                            <table>
                              <tr>
                                <th>Ширина: {{i.size.width}}</th>
                                <th>Высота: {{i.size.heigh}}</th>
                              </tr>
                            </table>
                          </div>
                        </div>
                      </div>
                    </a>
                        {% endfor %}


                        {%for i in producti%}
                    <div class="wrapper">
                        <a href="{%url 'one_tovar_adm' i.id%}"><div class="container">

                          <div class="top"><img src="{{i.image.url}}" alt=""> </div>
                          <div class="bottom">
                            <div class="left">
                              <div class="details">
                                <h2>{{i.name}}</h2>
                                <p>{{i.price}} р</p>
                              </div>
                              <div class="buy">
                              </div>
                            </div>
                            <div class="right">
                              <div class="done"><i class="material-icons">done</i></div>
                              <div class="details">
                                <h1>Chair</h1>
                                <p>Added to your cart</p>
                              </div>
                              <div class="remove"><i class="material-icons">clear</i></div>
                            </div>
                          </div>
                        </div>
                        <div class="inside">
                          <div class="icon"><i class="material-icons"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-info-circle" viewBox="0 0 16 16">
                            <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                            <path d="m8.93 6.588-2.29.287-.082.38.45.083c.294.07.352.176.288.469l-.738 3.468c-.194.897.105 1.319.808 1.319.545 0 1.178-.252 1.465-.598l.088-.416c-.2.176-.492.246-.686.246-.275 0-.375-.193-.304-.533L8.93 6.588zM9 4.5a1 1 0 1 1-2 0 1 1 0 0 1 2 0z"/>
                          </svg></i></div>
                          <div class="contents">
                            <table>
                              <tr>
                                <th>Ширина: {{i.size.width}}</th>
                                <th>Высота: {{i.size.heigh}}</th>
                              </tr>
                            </table>
                          </div>
                        </div>
                      </div>
                    </a>
                        {% endfor %}

             </div>
        </div>

{%endblock%}